spring.application.name=api-gateway

server.port=8081

# Gateway Routes
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.mvc.routes[1].id=user-service
spring.cloud.gateway.mvc.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/users/**

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT
jwt.secret=7a9f3c2e8b1d4f6a0e5c8b2d7f1a4e9c3b6d0f5a8e2c7b4d1f6a3e0c9b5d8f2a
jwt.expiration=86400000

