spring.application.name=api-gateway

server.port=8085

# Gateway Routes
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=hotel-service-hotels
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://HOTEL-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/hotels/**

spring.cloud.gateway.server.webmvc.routes[2].id=hotel-service-rooms
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://HOTEL-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/rooms/**

spring.cloud.gateway.server.webmvc.routes[3].id=payment-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/payments/**

spring.cloud.gateway.server.webmvc.routes[4].id=notification-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/notifications/**

spring.cloud.gateway.server.webmvc.routes[5].id=booking-service-bookings
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/bookings/**

spring.cloud.gateway.server.webmvc.routes[6].id=booking-service-availability
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/availability/**


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT
jwt.secret=7a9f3c2e8b1d4f6a0e5c8b2d7f1a4e9c3b6d0f5a8e2c7b4d1f6a3e0c9b5d8f2a
jwt.expiration=86400000

# Resilience4j Rate Limiting Configuration
resilience4j.ratelimiter.configs.gateway.limitForPeriod=50
resilience4j.ratelimiter.configs.gateway.limitRefreshPeriod=1s
resilience4j.ratelimiter.configs.gateway.timeoutDuration=0s
